context:
  name: certbot-dns-gehirn
  version: "5.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: ab7a26a6e1c58a93138c51d0cbaaa399148537b3724345a971718dce7a1ab00c

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - acme >=${{ version }}
    - certbot >=${{ version }}
    - dns-lexicon >=3.14.1

tests:
  - python:
      imports:
        - certbot_dns_gehirn
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://certbot.eff.org
  summary: Gehirn Infrastructure Service DNS Authenticator plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://certbot.eff.org
  repository: https://github.com/certbot/certbot

extra:
  recipe-maintainers:
    - pavelzw
